// js/data.js
// -----------------------------------------------------------------------
// Fuente única de datos: listado de países con nombre (ES/EN), continente,
// coordenadas (para distancia/dirección) y capital (ES/EN, para el modo
// "Capitales"). No contiene lógica de juego ni de UI.
// -----------------------------------------------------------------------

export const COUNTRIES = [
  // ---------- EUROPA ----------
  { code: "al", name_es: "Albania", name_en: "Albania", capital_es: "Tirana", capital_en: "Tirana", continent: "europe", lat: 41.1533, lon: 20.1683 },
  { code: "de", name_es: "Alemania", name_en: "Germany", capital_es: "Berlín", capital_en: "Berlin", continent: "europe", lat: 51.1657, lon: 10.4515 },
  { code: "ad", name_es: "Andorra", name_en: "Andorra", capital_es: "Andorra la Vieja", capital_en: "Andorra la Vella", continent: "europe", lat: 42.5063, lon: 1.5218 },
  { code: "at", name_es: "Austria", name_en: "Austria", capital_es: "Viena", capital_en: "Vienna", continent: "europe", lat: 47.5162, lon: 14.5501 },
  { code: "be", name_es: "Bélgica", name_en: "Belgium", capital_es: "Bruselas", capital_en: "Brussels", continent: "europe", lat: 50.5039, lon: 4.4699 },
  { code: "by", name_es: "Bielorrusia", name_en: "Belarus", capital_es: "Minsk", capital_en: "Minsk", continent: "europe", lat: 53.7098, lon: 27.9534 },
  { code: "ba", name_es: "Bosnia y Herzegovina", name_en: "Bosnia and Herzegovina", capital_es: "Sarajevo", capital_en: "Sarajevo", continent: "europe", lat: 43.9159, lon: 17.6791 },
  { code: "bg", name_es: "Bulgaria", name_en: "Bulgaria", capital_es: "Sofía", capital_en: "Sofia", continent: "europe", lat: 42.7339, lon: 25.4858 },
  { code: "cy", name_es: "Chipre", name_en: "Cyprus", capital_es: "Nicosia", capital_en: "Nicosia", continent: "europe", lat: 35.1264, lon: 33.4299 },
  { code: "va", name_es: "Ciudad del Vaticano", name_en: "Vatican City", capital_es: "Ciudad del Vaticano", capital_en: "Vatican City", continent: "europe", lat: 41.9029, lon: 12.4534 },
  { code: "hr", name_es: "Croacia", name_en: "Croatia", capital_es: "Zagreb", capital_en: "Zagreb", continent: "europe", lat: 45.1, lon: 15.2 },
  { code: "dk", name_es: "Dinamarca", name_en: "Denmark", capital_es: "Copenhague", capital_en: "Copenhagen", continent: "europe", lat: 56.2639, lon: 9.5018 },
  { code: "sk", name_es: "Eslovaquia", name_en: "Slovakia", capital_es: "Bratislava", capital_en: "Bratislava", continent: "europe", lat: 48.669, lon: 19.699 },
  { code: "si", name_es: "Eslovenia", name_en: "Slovenia", capital_es: "Liubliana", capital_en: "Ljubljana", continent: "europe", lat: 46.1512, lon: 14.9955 },
  { code: "es", name_es: "España", name_en: "Spain", capital_es: "Madrid", capital_en: "Madrid", continent: "europe", lat: 40.4637, lon: -3.7492 },
  { code: "ee", name_es: "Estonia", name_en: "Estonia", capital_es: "Tallin", capital_en: "Tallinn", continent: "europe", lat: 58.5953, lon: 25.0136 },
  { code: "fi", name_es: "Finlandia", name_en: "Finland", capital_es: "Helsinki", capital_en: "Helsinki", continent: "europe", lat: 61.9241, lon: 25.7482 },
  { code: "fr", name_es: "Francia", name_en: "France", capital_es: "París", capital_en: "Paris", continent: "europe", lat: 46.2276, lon: 2.2137 },
  { code: "gr", name_es: "Grecia", name_en: "Greece", capital_es: "Atenas", capital_en: "Athens", continent: "europe", lat: 39.0742, lon: 21.8243 },
  { code: "hu", name_es: "Hungría", name_en: "Hungary", capital_es: "Budapest", capital_en: "Budapest", continent: "europe", lat: 47.1625, lon: 19.5033 },
  { code: "ie", name_es: "Irlanda", name_en: "Ireland", capital_es: "Dublín", capital_en: "Dublin", continent: "europe", lat: 53.4129, lon: -8.2439 },
  { code: "is", name_es: "Islandia", name_en: "Iceland", capital_es: "Reikiavik", capital_en: "Reykjavik", continent: "europe", lat: 64.9631, lon: -19.0208 },
  { code: "it", name_es: "Italia", name_en: "Italy", capital_es: "Roma", capital_en: "Rome", continent: "europe", lat: 41.8719, lon: 12.5674 },
  { code: "lv", name_es: "Letonia", name_en: "Latvia", capital_es: "Riga", capital_en: "Riga", continent: "europe", lat: 56.8796, lon: 24.6032 },
  { code: "li", name_es: "Liechtenstein", name_en: "Liechtenstein", capital_es: "Vaduz", capital_en: "Vaduz", continent: "europe", lat: 47.166, lon: 9.5554 },
  { code: "lt", name_es: "Lituania", name_en: "Lithuania", capital_es: "Vilna", capital_en: "Vilnius", continent: "europe", lat: 55.1694, lon: 23.8813 },
  { code: "lu", name_es: "Luxemburgo", name_en: "Luxembourg", capital_es: "Luxemburgo", capital_en: "Luxembourg City", continent: "europe", lat: 49.8153, lon: 6.1296 },
  { code: "mk", name_es: "Macedonia del Norte", name_en: "North Macedonia", capital_es: "Skopie", capital_en: "Skopje", continent: "europe", lat: 41.6086, lon: 21.7453 },
  { code: "mt", name_es: "Malta", name_en: "Malta", capital_es: "La Valeta", capital_en: "Valletta", continent: "europe", lat: 35.9375, lon: 14.3754 },
  { code: "md", name_es: "Moldavia", name_en: "Moldova", capital_es: "Chisináu", capital_en: "Chisinau", continent: "europe", lat: 47.4116, lon: 28.3699 },
  { code: "mc", name_es: "Mónaco", name_en: "Monaco", capital_es: "Mónaco", capital_en: "Monaco", continent: "europe", lat: 43.7384, lon: 7.4246 },
  { code: "me", name_es: "Montenegro", name_en: "Montenegro", capital_es: "Podgorica", capital_en: "Podgorica", continent: "europe", lat: 42.7087, lon: 19.3744 },
  { code: "no", name_es: "Noruega", name_en: "Norway", capital_es: "Oslo", capital_en: "Oslo", continent: "europe", lat: 60.472, lon: 8.4689 },
  { code: "nl", name_es: "Países Bajos", name_en: "Netherlands", capital_es: "Ámsterdam", capital_en: "Amsterdam", continent: "europe", lat: 52.1326, lon: 5.2913 },
  { code: "pl", name_es: "Polonia", name_en: "Poland", capital_es: "Varsovia", capital_en: "Warsaw", continent: "europe", lat: 51.9194, lon: 19.1451 },
  { code: "pt", name_es: "Portugal", name_en: "Portugal", capital_es: "Lisboa", capital_en: "Lisbon", continent: "europe", lat: 39.3999, lon: -8.2245 },
  { code: "gb", name_es: "Reino Unido", name_en: "United Kingdom", capital_es: "Londres", capital_en: "London", continent: "europe", lat: 55.3781, lon: -3.436 },
  { code: "cz", name_es: "República Checa", name_en: "Czech Republic", capital_es: "Praga", capital_en: "Prague", continent: "europe", lat: 49.8175, lon: 15.473 },
  { code: "ro", name_es: "Rumania", name_en: "Romania", capital_es: "Bucarest", capital_en: "Bucharest", continent: "europe", lat: 45.9432, lon: 24.9668 },
  { code: "sm", name_es: "San Marino", name_en: "San Marino", capital_es: "San Marino", capital_en: "San Marino", continent: "europe", lat: 43.9424, lon: 12.4578 },
  { code: "rs", name_es: "Serbia", name_en: "Serbia", capital_es: "Belgrado", capital_en: "Belgrade", continent: "europe", lat: 44.0165, lon: 21.0059 },
  { code: "se", name_es: "Suecia", name_en: "Sweden", capital_es: "Estocolmo", capital_en: "Stockholm", continent: "europe", lat: 60.1282, lon: 18.6435 },
  { code: "ch", name_es: "Suiza", name_en: "Switzerland", capital_es: "Berna", capital_en: "Bern", continent: "europe", lat: 46.8182, lon: 8.2275 },
  { code: "ua", name_es: "Ucrania", name_en: "Ukraine", capital_es: "Kiev", capital_en: "Kyiv", continent: "europe", lat: 48.3794, lon: 31.1656 },

  // ---------- AMÉRICA DEL NORTE ----------
  { code: "ca", name_es: "Canadá", name_en: "Canada", capital_es: "Ottawa", capital_en: "Ottawa", continent: "namerica", lat: 56.1304, lon: -106.3468 },
  { code: "us", name_es: "Estados Unidos", name_en: "United States", capital_es: "Washington D. C.", capital_en: "Washington, D.C.", continent: "namerica", lat: 37.0902, lon: -95.7129 },
  { code: "mx", name_es: "México", name_en: "Mexico", capital_es: "Ciudad de México", capital_en: "Mexico City", continent: "namerica", lat: 23.6345, lon: -102.5528 },
  { code: "ag", name_es: "Antigua y Barbuda", name_en: "Antigua and Barbuda", capital_es: "Saint John's", capital_en: "Saint John's", continent: "namerica", lat: 17.0608, lon: -61.7964 },
  { code: "bs", name_es: "Bahamas", name_en: "Bahamas", capital_es: "Nasáu", capital_en: "Nassau", continent: "namerica", lat: 25.0343, lon: -77.3963 },
  { code: "bb", name_es: "Barbados", name_en: "Barbados", capital_es: "Bridgetown", capital_en: "Bridgetown", continent: "namerica", lat: 13.1939, lon: -59.5432 },
  { code: "bz", name_es: "Belice", name_en: "Belize", capital_es: "Belmopán", capital_en: "Belmopan", continent: "namerica", lat: 17.1899, lon: -88.4976 },
  { code: "cr", name_es: "Costa Rica", name_en: "Costa Rica", capital_es: "San José", capital_en: "San José", continent: "namerica", lat: 9.7489, lon: -83.7534 },
  { code: "cu", name_es: "Cuba", name_en: "Cuba", capital_es: "La Habana", capital_en: "Havana", continent: "namerica", lat: 21.5218, lon: -77.7812 },
  { code: "dm", name_es: "Dominica", name_en: "Dominica", capital_es: "Roseau", capital_en: "Roseau", continent: "namerica", lat: 15.415, lon: -61.371 },
  { code: "sv", name_es: "El Salvador", name_en: "El Salvador", capital_es: "San Salvador", capital_en: "San Salvador", continent: "namerica", lat: 13.7942, lon: -88.8965 },
  { code: "gd", name_es: "Granada", name_en: "Grenada", capital_es: "Saint George's", capital_en: "Saint George's", continent: "namerica", lat: 12.1165, lon: -61.679 },
  { code: "gt", name_es: "Guatemala", name_en: "Guatemala", capital_es: "Ciudad de Guatemala", capital_en: "Guatemala City", continent: "namerica", lat: 15.7835, lon: -90.2308 },
  { code: "ht", name_es: "Haití", name_en: "Haiti", capital_es: "Puerto Príncipe", capital_en: "Port-au-Prince", continent: "namerica", lat: 18.9712, lon: -72.2852 },
  { code: "hn", name_es: "Honduras", name_en: "Honduras", capital_es: "Tegucigalpa", capital_en: "Tegucigalpa", continent: "namerica", lat: 15.2, lon: -86.2419 },
  { code: "jm", name_es: "Jamaica", name_en: "Jamaica", capital_es: "Kingston", capital_en: "Kingston", continent: "namerica", lat: 18.1096, lon: -77.2975 },
  { code: "ni", name_es: "Nicaragua", name_en: "Nicaragua", capital_es: "Managua", capital_en: "Managua", continent: "namerica", lat: 12.8654, lon: -85.2072 },
  { code: "pa", name_es: "Panamá", name_en: "Panama", capital_es: "Ciudad de Panamá", capital_en: "Panama City", continent: "namerica", lat: 8.538, lon: -80.7821 },
  { code: "do", name_es: "República Dominicana", name_en: "Dominican Republic", capital_es: "Santo Domingo", capital_en: "Santo Domingo", continent: "namerica", lat: 18.7357, lon: -70.1627 },
  { code: "kn", name_es: "San Cristóbal y Nieves", name_en: "Saint Kitts and Nevis", capital_es: "Basseterre", capital_en: "Basseterre", continent: "namerica", lat: 17.3578, lon: -62.783 },
  { code: "vc", name_es: "San Vicente y las Granadinas", name_en: "Saint Vincent and the Grenadines", capital_es: "Kingstown", capital_en: "Kingstown", continent: "namerica", lat: 13.2528, lon: -61.1971 },
  { code: "lc", name_es: "Santa Lucía", name_en: "Saint Lucia", capital_es: "Castries", capital_en: "Castries", continent: "namerica", lat: 13.9094, lon: -60.9789 },
  { code: "tt", name_es: "Trinidad y Tobago", name_en: "Trinidad and Tobago", capital_es: "Puerto España", capital_en: "Port of Spain", continent: "namerica", lat: 10.6918, lon: -61.2225 },

  // ---------- AMÉRICA DEL SUR ----------
  { code: "ar", name_es: "Argentina", name_en: "Argentina", capital_es: "Buenos Aires", capital_en: "Buenos Aires", continent: "samerica", lat: -38.4161, lon: -63.6167 },
  { code: "bo", name_es: "Bolivia", name_en: "Bolivia", capital_es: "La Paz", capital_en: "La Paz", continent: "samerica", lat: -16.2902, lon: -63.5887 },
  { code: "br", name_es: "Brasil", name_en: "Brazil", capital_es: "Brasilia", capital_en: "Brasília", continent: "samerica", lat: -14.235, lon: -51.9253 },
  { code: "cl", name_es: "Chile", name_en: "Chile", capital_es: "Santiago", capital_en: "Santiago", continent: "samerica", lat: -35.6751, lon: -71.543 },
  { code: "co", name_es: "Colombia", name_en: "Colombia", capital_es: "Bogotá", capital_en: "Bogotá", continent: "samerica", lat: 4.5709, lon: -74.2973 },
  { code: "ec", name_es: "Ecuador", name_en: "Ecuador", capital_es: "Quito", capital_en: "Quito", continent: "samerica", lat: -1.8312, lon: -78.1834 },
  { code: "gy", name_es: "Guyana", name_en: "Guyana", capital_es: "Georgetown", capital_en: "Georgetown", continent: "samerica", lat: 4.8604, lon: -58.9302 },
  { code: "py", name_es: "Paraguay", name_en: "Paraguay", capital_es: "Asunción", capital_en: "Asunción", continent: "samerica", lat: -23.4425, lon: -58.4438 },
  { code: "pe", name_es: "Perú", name_en: "Peru", capital_es: "Lima", capital_en: "Lima", continent: "samerica", lat: -9.19, lon: -75.0152 },
  { code: "sr", name_es: "Surinam", name_en: "Suriname", capital_es: "Paramaribo", capital_en: "Paramaribo", continent: "samerica", lat: 3.9193, lon: -56.0278 },
  { code: "uy", name_es: "Uruguay", name_en: "Uruguay", capital_es: "Montevideo", capital_en: "Montevideo", continent: "samerica", lat: -32.5228, lon: -55.7658 },
  { code: "ve", name_es: "Venezuela", name_en: "Venezuela", capital_es: "Caracas", capital_en: "Caracas", continent: "samerica", lat: 6.4238, lon: -66.5897 },

  // ---------- ASIA ----------
  { code: "af", name_es: "Afganistán", name_en: "Afghanistan", capital_es: "Kabul", capital_en: "Kabul", continent: "asia", lat: 33.9391, lon: 67.7099 },
  { code: "sa", name_es: "Arabia Saudita", name_en: "Saudi Arabia", capital_es: "Riad", capital_en: "Riyadh", continent: "asia", lat: 23.8859, lon: 45.0792 },
  { code: "am", name_es: "Armenia", name_en: "Armenia", capital_es: "Ereván", capital_en: "Yerevan", continent: "asia", lat: 40.0691, lon: 45.0382 },
  { code: "az", name_es: "Azerbaiyán", name_en: "Azerbaijan", capital_es: "Bakú", capital_en: "Baku", continent: "asia", lat: 40.1431, lon: 47.5769 },
  { code: "bd", name_es: "Bangladés", name_en: "Bangladesh", capital_es: "Daca", capital_en: "Dhaka", continent: "asia", lat: 23.685, lon: 90.3563 },
  { code: "bh", name_es: "Baréin", name_en: "Bahrain", capital_es: "Manama", capital_en: "Manama", continent: "asia", lat: 25.9304, lon: 50.6378 },
  { code: "bn", name_es: "Brunéi", name_en: "Brunei", capital_es: "Bandar Seri Begawan", capital_en: "Bandar Seri Begawan", continent: "asia", lat: 4.5353, lon: 114.7277 },
  { code: "bt", name_es: "Bután", name_en: "Bhutan", capital_es: "Timbu", capital_en: "Thimphu", continent: "asia", lat: 27.5142, lon: 90.4336 },
  { code: "kh", name_es: "Camboya", name_en: "Cambodia", capital_es: "Nom Pen", capital_en: "Phnom Penh", continent: "asia", lat: 12.5657, lon: 104.991 },
  { code: "qa", name_es: "Catar", name_en: "Qatar", capital_es: "Doha", capital_en: "Doha", continent: "asia", lat: 25.3548, lon: 51.1839 },
  { code: "cn", name_es: "China", name_en: "China", capital_es: "Pekín", capital_en: "Beijing", continent: "asia", lat: 35.8617, lon: 104.1954 },
  { code: "kp", name_es: "Corea del Norte", name_en: "North Korea", capital_es: "Pionyang", capital_en: "Pyongyang", continent: "asia", lat: 40.3399, lon: 127.5101 },
  { code: "kr", name_es: "Corea del Sur", name_en: "South Korea", capital_es: "Seúl", capital_en: "Seoul", continent: "asia", lat: 35.9078, lon: 127.7669 },
  { code: "ae", name_es: "Emiratos Árabes Unidos", name_en: "United Arab Emirates", capital_es: "Abu Dabi", capital_en: "Abu Dhabi", continent: "asia", lat: 23.4241, lon: 53.8478 },
  { code: "ph", name_es: "Filipinas", name_en: "Philippines", capital_es: "Manila", capital_en: "Manila", continent: "asia", lat: 12.8797, lon: 121.774 },
  { code: "ge", name_es: "Georgia", name_en: "Georgia", capital_es: "Tiflis", capital_en: "Tbilisi", continent: "asia", lat: 42.3154, lon: 43.3569 },
  { code: "in", name_es: "India", name_en: "India", capital_es: "Nueva Delhi", capital_en: "New Delhi", continent: "asia", lat: 20.5937, lon: 78.9629 },
  { code: "id", name_es: "Indonesia", name_en: "Indonesia", capital_es: "Yakarta", capital_en: "Jakarta", continent: "asia", lat: -0.7893, lon: 113.9213 },
  { code: "iq", name_es: "Irak", name_en: "Iraq", capital_es: "Bagdad", capital_en: "Baghdad", continent: "asia", lat: 33.2232, lon: 43.6793 },
  { code: "ir", name_es: "Irán", name_en: "Iran", capital_es: "Teherán", capital_en: "Tehran", continent: "asia", lat: 32.4279, lon: 53.688 },
  { code: "il", name_es: "Israel", name_en: "Israel", capital_es: "Jerusalén", capital_en: "Jerusalem", continent: "asia", lat: 31.0461, lon: 34.8516 },
  { code: "jp", name_es: "Japón", name_en: "Japan", capital_es: "Tokio", capital_en: "Tokyo", continent: "asia", lat: 36.2048, lon: 138.2529 },
  { code: "jo", name_es: "Jordania", name_en: "Jordan", capital_es: "Amán", capital_en: "Amman", continent: "asia", lat: 30.5852, lon: 36.2384 },
  { code: "kz", name_es: "Kazajistán", name_en: "Kazakhstan", capital_es: "Astaná", capital_en: "Astana", continent: "asia", lat: 48.0196, lon: 66.9237 },
  { code: "kg", name_es: "Kirguistán", name_en: "Kyrgyzstan", capital_es: "Biskek", capital_en: "Bishkek", continent: "asia", lat: 41.2044, lon: 74.7661 },
  { code: "kw", name_es: "Kuwait", name_en: "Kuwait", capital_es: "Kuwait", capital_en: "Kuwait City", continent: "asia", lat: 29.3117, lon: 47.4818 },
  { code: "la", name_es: "Laos", name_en: "Laos", capital_es: "Vientián", capital_en: "Vientiane", continent: "asia", lat: 19.8563, lon: 102.4955 },
  { code: "lb", name_es: "Líbano", name_en: "Lebanon", capital_es: "Beirut", capital_en: "Beirut", continent: "asia", lat: 33.8547, lon: 35.8623 },
  { code: "my", name_es: "Malasia", name_en: "Malaysia", capital_es: "Kuala Lumpur", capital_en: "Kuala Lumpur", continent: "asia", lat: 4.2105, lon: 101.9758 },
  { code: "mv", name_es: "Maldivas", name_en: "Maldives", capital_es: "Malé", capital_en: "Malé", continent: "asia", lat: 3.2028, lon: 73.2207 },
  { code: "mn", name_es: "Mongolia", name_en: "Mongolia", capital_es: "Ulán Bator", capital_en: "Ulaanbaatar", continent: "asia", lat: 46.8625, lon: 103.8467 },
  { code: "mm", name_es: "Myanmar", name_en: "Myanmar", capital_es: "Naipyidó", capital_en: "Naypyidaw", continent: "asia", lat: 21.9162, lon: 95.956 },
  { code: "np", name_es: "Nepal", name_en: "Nepal", capital_es: "Katmandú", capital_en: "Kathmandu", continent: "asia", lat: 28.3949, lon: 84.124 },
  { code: "om", name_es: "Omán", name_en: "Oman", capital_es: "Mascate", capital_en: "Muscat", continent: "asia", lat: 21.4735, lon: 55.9754 },
  { code: "pk", name_es: "Pakistán", name_en: "Pakistan", capital_es: "Islamabad", capital_en: "Islamabad", continent: "asia", lat: 30.3753, lon: 69.3451 },
  { code: "ps", name_es: "Palestina", name_en: "Palestine", capital_es: "Ramala", capital_en: "Ramallah", continent: "asia", lat: 31.9522, lon: 35.2332 },
  { code: "ru", name_es: "Rusia", name_en: "Russia", capital_es: "Moscú", capital_en: "Moscow", continent: "asia", lat: 61.524, lon: 105.3188 },
  { code: "sg", name_es: "Singapur", name_en: "Singapore", capital_es: "Singapur", capital_en: "Singapore", continent: "asia", lat: 1.3521, lon: 103.8198 },
  { code: "sy", name_es: "Siria", name_en: "Syria", capital_es: "Damasco", capital_en: "Damascus", continent: "asia", lat: 34.8021, lon: 38.9968 },
  { code: "lk", name_es: "Sri Lanka", name_en: "Sri Lanka", capital_es: "Colombo", capital_en: "Colombo", continent: "asia", lat: 7.8731, lon: 80.7718 },
  { code: "th", name_es: "Tailandia", name_en: "Thailand", capital_es: "Bangkok", capital_en: "Bangkok", continent: "asia", lat: 15.87, lon: 100.9925 },
  { code: "tw", name_es: "Taiwán", name_en: "Taiwan", capital_es: "Taipéi", capital_en: "Taipei", continent: "asia", lat: 23.6978, lon: 120.9605 },
  { code: "tj", name_es: "Tayikistán", name_en: "Tajikistan", capital_es: "Dusambé", capital_en: "Dushanbe", continent: "asia", lat: 38.861, lon: 71.2761 },
  { code: "tl", name_es: "Timor Oriental", name_en: "Timor-Leste", capital_es: "Dili", capital_en: "Dili", continent: "asia", lat: -8.8742, lon: 125.7275 },
  { code: "tm", name_es: "Turkmenistán", name_en: "Turkmenistan", capital_es: "Asjabad", capital_en: "Ashgabat", continent: "asia", lat: 38.9697, lon: 59.5563 },
  { code: "tr", name_es: "Turquía", name_en: "Turkey", capital_es: "Ankara", capital_en: "Ankara", continent: "asia", lat: 38.9637, lon: 35.2433 },
  { code: "uz", name_es: "Uzbekistán", name_en: "Uzbekistan", capital_es: "Taskent", capital_en: "Tashkent", continent: "asia", lat: 41.3775, lon: 64.5853 },
  { code: "vn", name_es: "Vietnam", name_en: "Vietnam", capital_es: "Hanói", capital_en: "Hanoi", continent: "asia", lat: 14.0583, lon: 108.2772 },
  { code: "ye", name_es: "Yemen", name_en: "Yemen", capital_es: "Saná", capital_en: "Sana'a", continent: "asia", lat: 15.5527, lon: 48.5164 },

  // ---------- ÁFRICA ----------
  { code: "dz", name_es: "Argelia", name_en: "Algeria", capital_es: "Argel", capital_en: "Algiers", continent: "africa", lat: 28.0339, lon: 1.6596 },
  { code: "ao", name_es: "Angola", name_en: "Angola", capital_es: "Luanda", capital_en: "Luanda", continent: "africa", lat: -11.2027, lon: 17.8739 },
  { code: "bj", name_es: "Benín", name_en: "Benin", capital_es: "Porto Novo", capital_en: "Porto-Novo", continent: "africa", lat: 9.3077, lon: 2.3158 },
  { code: "bw", name_es: "Botsuana", name_en: "Botswana", capital_es: "Gaborone", capital_en: "Gaborone", continent: "africa", lat: -22.3285, lon: 24.6849 },
  { code: "bf", name_es: "Burkina Faso", name_en: "Burkina Faso", capital_es: "Uagadugú", capital_en: "Ouagadougou", continent: "africa", lat: 12.2383, lon: -1.5616 },
  { code: "bi", name_es: "Burundi", name_en: "Burundi", capital_es: "Gitega", capital_en: "Gitega", continent: "africa", lat: -3.3731, lon: 29.9189 },
  { code: "cv", name_es: "Cabo Verde", name_en: "Cape Verde", capital_es: "Praia", capital_en: "Praia", continent: "africa", lat: 16.5388, lon: -23.0418 },
  { code: "cm", name_es: "Camerún", name_en: "Cameroon", capital_es: "Yaundé", capital_en: "Yaoundé", continent: "africa", lat: 3.848, lon: 11.5021 },
  { code: "td", name_es: "Chad", name_en: "Chad", capital_es: "Yamena", capital_en: "N'Djamena", continent: "africa", lat: 15.4542, lon: 18.7322 },
  { code: "km", name_es: "Comoras", name_en: "Comoros", capital_es: "Moroni", capital_en: "Moroni", continent: "africa", lat: -11.875, lon: 43.8722 },
  { code: "cg", name_es: "República del Congo", name_en: "Republic of the Congo", capital_es: "Brazzaville", capital_en: "Brazzaville", continent: "africa", lat: -0.228, lon: 15.8277 },
  { code: "cd", name_es: "República Democrática del Congo", name_en: "Democratic Republic of the Congo", capital_es: "Kinsasa", capital_en: "Kinshasa", continent: "africa", lat: -4.0383, lon: 21.7587 },
  { code: "ci", name_es: "Costa de Marfil", name_en: "Ivory Coast", capital_es: "Yamusukro", capital_en: "Yamoussoukro", continent: "africa", lat: 7.54, lon: -5.5471 },
  { code: "dj", name_es: "Yibuti", name_en: "Djibouti", capital_es: "Yibuti", capital_en: "Djibouti", continent: "africa", lat: 11.8251, lon: 42.5903 },
  { code: "eg", name_es: "Egipto", name_en: "Egypt", capital_es: "El Cairo", capital_en: "Cairo", continent: "africa", lat: 26.8206, lon: 30.8025 },
  { code: "er", name_es: "Eritrea", name_en: "Eritrea", capital_es: "Asmara", capital_en: "Asmara", continent: "africa", lat: 15.1794, lon: 39.7823 },
  { code: "sz", name_es: "Esuatini", name_en: "Eswatini", capital_es: "Mbabane", capital_en: "Mbabane", continent: "africa", lat: -26.5225, lon: 31.4659 },
  { code: "et", name_es: "Etiopía", name_en: "Ethiopia", capital_es: "Adís Abeba", capital_en: "Addis Ababa", continent: "africa", lat: 9.145, lon: 40.4897 },
  { code: "ga", name_es: "Gabón", name_en: "Gabon", capital_es: "Libreville", capital_en: "Libreville", continent: "africa", lat: -0.8037, lon: 11.6094 },
  { code: "gm", name_es: "Gambia", name_en: "Gambia", capital_es: "Banjul", capital_en: "Banjul", continent: "africa", lat: 13.4432, lon: -15.3101 },
  { code: "gh", name_es: "Ghana", name_en: "Ghana", capital_es: "Acra", capital_en: "Accra", continent: "africa", lat: 7.9465, lon: -1.0232 },
  { code: "gn", name_es: "Guinea", name_en: "Guinea", capital_es: "Conakri", capital_en: "Conakry", continent: "africa", lat: 9.9456, lon: -9.6966 },
  { code: "gw", name_es: "Guinea-Bisáu", name_en: "Guinea-Bissau", capital_es: "Bisáu", capital_en: "Bissau", continent: "africa", lat: 11.8037, lon: -15.1804 },
  { code: "gq", name_es: "Guinea Ecuatorial", name_en: "Equatorial Guinea", capital_es: "Malabo", capital_en: "Malabo", continent: "africa", lat: 1.6508, lon: 10.2679 },
  { code: "ke", name_es: "Kenia", name_en: "Kenya", capital_es: "Nairobi", capital_en: "Nairobi", continent: "africa", lat: -0.0236, lon: 37.9062 },
  { code: "ls", name_es: "Lesoto", name_en: "Lesotho", capital_es: "Maseru", capital_en: "Maseru", continent: "africa", lat: -29.6099, lon: 28.2336 },
  { code: "lr", name_es: "Liberia", name_en: "Liberia", capital_es: "Monrovia", capital_en: "Monrovia", continent: "africa", lat: 6.4281, lon: -9.4295 },
  { code: "ly", name_es: "Libia", name_en: "Libya", capital_es: "Trípoli", capital_en: "Tripoli", continent: "africa", lat: 26.3351, lon: 17.2283 },
  { code: "mg", name_es: "Madagascar", name_en: "Madagascar", capital_es: "Antananarivo", capital_en: "Antananarivo", continent: "africa", lat: -18.7669, lon: 46.8691 },
  { code: "mw", name_es: "Malaui", name_en: "Malawi", capital_es: "Lilongüe", capital_en: "Lilongwe", continent: "africa", lat: -13.2543, lon: 34.3015 },
  { code: "ml", name_es: "Malí", name_en: "Mali", capital_es: "Bamako", capital_en: "Bamako", continent: "africa", lat: 17.5707, lon: -3.9962 },
  { code: "ma", name_es: "Marruecos", name_en: "Morocco", capital_es: "Rabat", capital_en: "Rabat", continent: "africa", lat: 31.7917, lon: -7.0926 },
  { code: "mu", name_es: "Mauricio", name_en: "Mauritius", capital_es: "Port Louis", capital_en: "Port Louis", continent: "africa", lat: -20.3484, lon: 57.5522 },
  { code: "mr", name_es: "Mauritania", name_en: "Mauritania", capital_es: "Nuakchot", capital_en: "Nouakchott", continent: "africa", lat: 21.0079, lon: -10.9408 },
  { code: "mz", name_es: "Mozambique", name_en: "Mozambique", capital_es: "Maputo", capital_en: "Maputo", continent: "africa", lat: -18.6657, lon: 35.5296 },
  { code: "na", name_es: "Namibia", name_en: "Namibia", capital_es: "Windhoek", capital_en: "Windhoek", continent: "africa", lat: -22.9576, lon: 18.4904 },
  { code: "ne", name_es: "Níger", name_en: "Niger", capital_es: "Niamey", capital_en: "Niamey", continent: "africa", lat: 17.6078, lon: 8.0817 },
  { code: "ng", name_es: "Nigeria", name_en: "Nigeria", capital_es: "Abuya", capital_en: "Abuja", continent: "africa", lat: 9.082, lon: 8.6753 },
  { code: "cf", name_es: "República Centroafricana", name_en: "Central African Republic", capital_es: "Bangui", capital_en: "Bangui", continent: "africa", lat: 6.6111, lon: 20.9394 },
  { code: "rw", name_es: "Ruanda", name_en: "Rwanda", capital_es: "Kigali", capital_en: "Kigali", continent: "africa", lat: -1.9403, lon: 29.8739 },
  { code: "st", name_es: "Santo Tomé y Príncipe", name_en: "Sao Tome and Principe", capital_es: "Santo Tomé", capital_en: "São Tomé", continent: "africa", lat: 0.1864, lon: 6.6131 },
  { code: "sn", name_es: "Senegal", name_en: "Senegal", capital_es: "Dakar", capital_en: "Dakar", continent: "africa", lat: 14.4974, lon: -14.4524 },
  { code: "sc", name_es: "Seychelles", name_en: "Seychelles", capital_es: "Victoria", capital_en: "Victoria", continent: "africa", lat: -4.6796, lon: 55.492 },
  { code: "sl", name_es: "Sierra Leona", name_en: "Sierra Leone", capital_es: "Freetown", capital_en: "Freetown", continent: "africa", lat: 8.4606, lon: -11.7799 },
  { code: "so", name_es: "Somalia", name_en: "Somalia", capital_es: "Mogadiscio", capital_en: "Mogadishu", continent: "africa", lat: 5.1521, lon: 46.1996 },
  { code: "za", name_es: "Sudáfrica", name_en: "South Africa", capital_es: "Pretoria", capital_en: "Pretoria", continent: "africa", lat: -30.5595, lon: 22.9375 },
  { code: "sd", name_es: "Sudán", name_en: "Sudan", capital_es: "Jartum", capital_en: "Khartoum", continent: "africa", lat: 12.8628, lon: 30.2176 },
  { code: "ss", name_es: "Sudán del Sur", name_en: "South Sudan", capital_es: "Yuba", capital_en: "Juba", continent: "africa", lat: 6.877, lon: 31.307 },
  { code: "tz", name_es: "Tanzania", name_en: "Tanzania", capital_es: "Dodoma", capital_en: "Dodoma", continent: "africa", lat: -6.369, lon: 34.8888 },
  { code: "tg", name_es: "Togo", name_en: "Togo", capital_es: "Lomé", capital_en: "Lomé", continent: "africa", lat: 8.6195, lon: 0.8248 },
  { code: "tn", name_es: "Túnez", name_en: "Tunisia", capital_es: "Túnez", capital_en: "Tunis", continent: "africa", lat: 33.8869, lon: 9.5375 },
  { code: "ug", name_es: "Uganda", name_en: "Uganda", capital_es: "Kampala", capital_en: "Kampala", continent: "africa", lat: 1.3733, lon: 32.2903 },
  { code: "zm", name_es: "Zambia", name_en: "Zambia", capital_es: "Lusaka", capital_en: "Lusaka", continent: "africa", lat: -13.1339, lon: 27.8493 },
  { code: "zw", name_es: "Zimbabue", name_en: "Zimbabwe", capital_es: "Harare", capital_en: "Harare", continent: "africa", lat: -19.0154, lon: 29.1549 },

  // ---------- OCEANÍA ----------
  { code: "au", name_es: "Australia", name_en: "Australia", capital_es: "Camberra", capital_en: "Canberra", continent: "oceania", lat: -25.2744, lon: 133.7751 },
  { code: "fj", name_es: "Fiyi", name_en: "Fiji", capital_es: "Suva", capital_en: "Suva", continent: "oceania", lat: -17.7134, lon: 178.065 },
  { code: "mh", name_es: "Islas Marshall", name_en: "Marshall Islands", capital_es: "Majuro", capital_en: "Majuro", continent: "oceania", lat: 7.1315, lon: 171.1845 },
  { code: "sb", name_es: "Islas Salomón", name_en: "Solomon Islands", capital_es: "Honiara", capital_en: "Honiara", continent: "oceania", lat: -9.6457, lon: 160.1562 },
  { code: "ki", name_es: "Kiribati", name_en: "Kiribati", capital_es: "Tarawa Sur", capital_en: "South Tarawa", continent: "oceania", lat: 1.4424, lon: 172.9772 },
  { code: "fm", name_es: "Micronesia", name_en: "Micronesia", capital_es: "Palikir", capital_en: "Palikir", continent: "oceania", lat: 7.4256, lon: 150.5508 },
  { code: "nr", name_es: "Nauru", name_en: "Nauru", capital_es: "Yaren", capital_en: "Yaren", continent: "oceania", lat: -0.5228, lon: 166.9315 },
  { code: "nz", name_es: "Nueva Zelanda", name_en: "New Zealand", capital_es: "Wellington", capital_en: "Wellington", continent: "oceania", lat: -40.9006, lon: 174.886 },
  { code: "pw", name_es: "Palaos", name_en: "Palau", capital_es: "Ngerulmud", capital_en: "Ngerulmud", continent: "oceania", lat: 7.515, lon: 134.5825 },
  { code: "pg", name_es: "Papúa Nueva Guinea", name_en: "Papua New Guinea", capital_es: "Port Moresby", capital_en: "Port Moresby", continent: "oceania", lat: -6.3149, lon: 143.9555 },
  { code: "ws", name_es: "Samoa", name_en: "Samoa", capital_es: "Apia", capital_en: "Apia", continent: "oceania", lat: -13.759, lon: -172.1046 },
  { code: "to", name_es: "Tonga", name_en: "Tonga", capital_es: "Nukuʻalofa", capital_en: "Nukuʻalofa", continent: "oceania", lat: -21.179, lon: -175.1982 },
  { code: "tv", name_es: "Tuvalu", name_en: "Tuvalu", capital_es: "Funafuti", capital_en: "Funafuti", continent: "oceania", lat: -7.1095, lon: 177.6493 },
  { code: "vu", name_es: "Vanuatu", name_en: "Vanuatu", capital_es: "Port Vila", capital_en: "Port Vila", continent: "oceania", lat: -15.3767, lon: 166.9592 },
];

/** Devuelve el nombre del país en el idioma indicado ("es" | "en"). */
export function countryName(country, lang) {
  return lang === "es" ? country.name_es : country.name_en;
}

/** Devuelve la capital del país en el idioma indicado ("es" | "en"). */
export function countryCapital(country, lang) {
  return lang === "es" ? country.capital_es : country.capital_en;
}
